import * as process from 'node:process'
import { defineConfig } from 'oxfmt'

export default defineConfig({
  arrowParens: 'avoid',
  bracketSameLine: true,
  bracketSpacing: true,
  embeddedLanguageFormatting: 'auto',
  endOfLine: process.platform === 'win32' ? 'crlf' : 'lf',
  htmlWhitespaceSensitivity: 'strict',
  ignorePatterns: ['packages/**/dist/'],
  insertFinalNewline: true,
  jsdoc: {
    addDefaultToDescription: true,
    bracketSpacing: true,
    capitalizeDescriptions: true,
    commentLineStrategy: 'multiline',
    descriptionTag: true,
    descriptionWithDot: false,
    keepUnparsableExampleIndent: true,
    lineWrappingStyle: 'balance',
    preferCodeFences: true,
    separateReturnsFromParam: false,
    separateTagGroups: true,
  },
  jsxSingleQuote: false,
  objectWrap: 'preserve',
  printWidth: 80,
  proseWrap: 'preserve',
  quoteProps: 'as-needed',
  semi: false,
  singleAttributePerLine: false,
  singleQuote: true,
  sortImports: {
    customGroups: [
      {
        elementNamePattern: ['vue', 'vue-**'],
        groupName: 'vue-libs',
      },
      {
        elementNamePattern: ['vitepress', 'vitepress-**'],
        groupName: 'vitepress-libs',
      },
    ],
    groups: [
      'type-import',
      'vue-libs',
      'vitepress-libs',
      ['value-builtin', 'value-external'],
      'type-internal',
      'value-internal',
      ['type-parent', 'type-sibling', 'type-index'],
      ['value-parent', 'value-sibling', 'value-index'],
      'unknown',
    ],
    newlinesBetween: false,
  },
  sortPackageJson: {
    sortScripts: true,
  },
  tabWidth: 2,
  trailingComma: 'all',
  useTabs: false,
  vueIndentScriptAndStyle: false,
})
