import { defineConfig } from 'oxlint'

export default defineConfig({
  categories: {
    correctness: 'error',
    // nursery: 'warn',
    // pedantic: 'warn',
    // perf: 'warn',
    // restriction: 'warn',
    // style: 'warn',
    // suspicious: 'warn',
  },
  plugins: ['vue', 'typescript', 'oxc', 'promise'],
  rules: {
    'eslint/no-ternary': 'allow',
    'eslint/no-unused-vars': 'error',
    'vue/component-definition-name-casing': ['warn', 'PascalCase'],
    'vue/define-emits-declaration': ['error', 'type-based'],
    'vue/define-props-declaration': ['error', 'type-based'],
    'vue/define-props-destructuring': ['error', { destructure: 'always' }],
    'vue/max-props': 'off',
    'vue/next-tick-style': ['error', 'promise'],
    'vue/no-arrow-functions-in-watch': 'error',
    'vue/no-async-in-computed-properties': 'error',
    'vue/no-computed-properties-in-data': 'error',
    'vue/no-deprecated-data-object-declaration': 'error',
    'vue/no-deprecated-delete-set': 'error',
    'vue/no-deprecated-destroyed-lifecycle': 'error',
    'vue/no-deprecated-events-api': 'error',
    'vue/no-deprecated-model-definition': 'error',
    'vue/no-deprecated-props-default-this': 'error',
    'vue/no-deprecated-vue-config-keycodes': 'error',
    'vue/no-dupe-keys': 'error',
    'vue/no-export-in-script-setup': 'error',
    'vue/no-expose-after-await': 'error',
    'vue/no-import-compiler-macros': 'error',
    'vue/no-lifecycle-after-await': 'error',
    'vue/no-multiple-slot-args': 'error',
    'vue/no-required-prop-with-default': 'error',
    'vue/no-reserved-component-names': 'error',
    'vue/no-reserved-keys': 'error',
    'vue/no-reserved-props': 'error',
    'vue/no-shared-component-data': 'error',
    'vue/no-side-effects-in-computed-properties': 'error',
    'vue/no-this-in-before-route-enter': 'error',
    'vue/no-watch-after-await': 'error',
    'vue/prefer-import-from-vue': 'warn',
    'vue/prop-name-casing': ['warn', 'camelCase'],
    'vue/require-default-export': 'error',
    'vue/require-default-prop': 'warn',
    'vue/require-direct-export': 'warn',
    'vue/require-prop-type-constructor': 'warn',
    'vue/require-prop-types': 'warn',
    'vue/require-render-return': 'error',
    'vue/require-slots-as-functions': 'error',
    'vue/require-typed-ref': 'error',
    'vue/return-in-computed-property': 'error',
    'vue/return-in-emits-validator': 'error',
    'vue/valid-define-emits': 'error',
    'vue/valid-define-options': 'error',
    'vue/valid-define-props': 'error',
    'vue/valid-next-tick': 'error',
  },
})
