packages:
  - packages/*
  - docs
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
catalogMode: strict
catalog:
  '@microsoft/api-extractor': ^7.58.9
  '@tsconfig/node24': ^24.0.4
  '@tsdown/css': ^0.22.7
  '@types/node': ^26.1.1
  '@vitejs/plugin-vue-jsx': ^5.1.6
  '@vue/tsconfig': ^0.9.1
  husky: ^9.1.7
  oxfmt: ^0.59.0
  oxlint: ^1.74.0
  sass-embedded: ^1.100.0
  tsdown: ^0.22.7
  typescript: ^7.0.2
  vitepress: 2.0.0-alpha.18
  vue: ^3.5.39
