packages:
  - packages/*
  - docs
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
catalogMode: strict
catalog:
  '@giscus/vue': ^3.1.1
  '@mdit/plugin-katex': ^1.0.1
  '@mdit/plugin-mathjax': ^1.1.0
  '@microsoft/api-extractor': ^7.58.9
  '@tsconfig/node24': ^24.0.4
  '@tsdown/css': ^0.22.7
  '@types/markdown-it': ^14.1.2
  '@types/node': ^26.1.1
  '@vue/tsconfig': ^0.9.1
  husky: ^9.1.7
  oxfmt: ^0.59.0
  oxlint: ^1.74.0
  sass-embedded: ^1.100.0
  tsdown: ^0.22.7
  twikoo: ^1.7.14
  typescript: ^6
  unplugin-vue: ^7.2.0
  vitepress: 2.0.0-alpha.18
  vue: ^3.5.39
  vue-tsc: ^3.3.7
